DROP TABLE TAG_VALUES IF EXISTS;
CREATE TABLE TAG_VALUES (TAG INT, NAME VARCHAR(255), VALUE VARCHAR(255));

INSERT INTO TAG_VALUES VALUES(1, 'A', 'A');
INSERT INTO TAG_VALUES VALUES(1, 'B', 'B');
INSERT INTO TAG_VALUES VALUES(39, 'X', 'X');
INSERT INTO TAG_VALUES VALUES(39, 'B', 'B');
